import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,writeFileSync,readFileSync,realpathSync,mkdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {get as httpGet} from 'node:http';
import {chromium} from 'playwright';
import {initProject} from '../src/project.mjs';
import {ensureDashboard,stopDashboard} from '../src/runtime/dashboard.mjs';
import {runtimePaths} from '../src/runtime/paths.mjs';
import {readDashboardPreferences,saveDashboardPreferences} from '../src/dashboard-preferences.mjs';

test('real dashboard supports quiet defaults, shared settings, premium states and accessible mobile navigation',{timeout:90000},async t=>{
  const root=realpathSync(mkdtempSync(resolve(tmpdir(),'ewai-dashboard-navigation-')));
  const captures=resolve(import.meta.dirname,'../SPECS/6.Build/configurable-project-dashboard/ui-design-assets/implementation');
  const capture=async name=>{if(process.env.EWAI_CAPTURE_DASHBOARD==='1'){mkdirSync(captures,{recursive:true});await page.locator('.dashboard-view:visible').evaluateAll(elements=>elements.forEach(el=>{el.scrollTop=0;}));await page.screenshot({path:resolve(captures,name+'.png'),fullPage:true});}};
  let browser;
  t.after(async()=>{await browser?.close();await stopDashboard(root);rmSync(root,{recursive:true,force:true});});
  initProject(root,{name:'Sidebar fixture'});
  let started;
  try{started=await ensureDashboard(root,{home:resolve(root,'isolated-home'),premiumCheck:Promise.resolve({access:'unavailable',installed:false,verified:false,accessReason:'licence-not-configured'})});}catch(error){t.diagnostic(readFileSync(runtimePaths(root).dashboardLogPath,'utf8'));throw error;}
  assert.equal(started.status,'running');
  browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],requests=[];
  page.on('pageerror',error=>errors.push(error.message));page.on('request',r=>requests.push(new URL(r.url()).pathname));
  await page.goto(started.url);await page.locator('#dashboardSidebar').waitFor();
  await page.waitForFunction(()=>document.querySelector('#configurationNav')?.disabled===false);
  assert.equal(await page.locator('#dashboardSidebar [data-optional-view]:visible').count(),0);
  assert.ok(!requests.some(p=>['/api/portfolio','/api/team-hub','/api/security-validation','/api/starters'].includes(p)));
  await capture('desktop-board');
  await page.locator('#configurationNav').click();assert.equal(await page.locator('#configurationView input[type=checkbox]').count(),9);
  await page.getByRole('checkbox',{name:'Show Portfolio',exact:true}).check();await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await page.getByText('Dashboard preferences saved.',{exact:true}).waitFor();
  await page.reload();await page.waitForFunction(()=>document.querySelector('#configurationNav')?.disabled===false);
  assert.equal(await page.locator('#dashboardSidebar [data-view=portfolio]:visible').count(),1);
  await page.locator('#configurationNav').click();
  assert.equal(await page.locator('#configurationNav').getAttribute('aria-current'),'page');
  await page.getByRole('checkbox',{name:'Show Team Hub',exact:true}).check();
  await page.locator('#refresh').click();assert.equal(await page.getByRole('checkbox',{name:'Show Team Hub',exact:true}).isChecked(),true);
  const external=readDashboardPreferences(root);
  saveDashboardPreferences(root,{confirmed:true,expectedDigest:external.digest,preferences:{...external.preferences,optional_views:{...external.preferences.optional_views,starters:true}}});
  await page.locator('#refresh').click();await page.getByText('Project settings changed elsewhere. Your draft is kept; cancel to reload before saving.',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByText('Project configuration changed. Reload the settings and try again.',{exact:true}).waitFor();
  assert.equal(await page.getByRole('checkbox',{name:'Show Team Hub',exact:true}).isChecked(),true);
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await page.getByText('Unsaved changes discarded.',{exact:true}).waitFor();
  assert.equal(await page.getByRole('checkbox',{name:'Show Team Hub',exact:true}).isChecked(),false);
  assert.equal(await page.getByRole('checkbox',{name:'Show Starters',exact:true}).isChecked(),true);
  for(const checkbox of await page.locator('#configurationView input[type=checkbox]').all())await checkbox.check();
  await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByText('Dashboard preferences saved.',{exact:true}).waitFor();
  assert.equal(await page.locator('#dashboardSidebar [data-optional-view]:visible').count(),9);
  await capture('desktop-configuration');
  await page.locator('#sidebarCollapse').click();await page.waitForFunction(()=>document.querySelector('#app').classList.contains('sidebar-collapsed'));
  await page.locator('#configurationNav').click();assert.equal(await page.locator('#configurationView').isVisible(),true);
  await capture('collapsed-configuration');
  const checkin=runtimePaths(root).checkinStatePath;
  writeFileSync(checkin,JSON.stringify({schema:'ewai.checkin-state/v1',premium:{access:'available',installed:true,verified:true,version:'0.1.1'}}));
  await page.locator('#refresh').click();await page.waitForFunction(()=>document.querySelector('#premiumLearn').hidden===true);
  assert.equal(await page.locator('#premiumSetup').isVisible(),false);assert.equal(await page.getByRole('button',{name:'Manage licence',exact:true}).isVisible(),true);
  writeFileSync(checkin,JSON.stringify({schema:'ewai.checkin-state/v1',premium:{access:'unknown',installed:true,verified:true}}));
  await page.locator('#refresh').click();await page.waitForFunction(()=>document.querySelector('#premiumLearn').hidden===false);
  await page.setViewportSize({width:390,height:844});await page.locator('#sidebarOpen').click();
  assert.equal(await page.locator('#dashboardSidebar').getAttribute('aria-modal'),'true');
  assert.equal(await page.locator('.app-bar').evaluate(el=>el.inert),true);
  await capture('mobile-drawer');
  await page.keyboard.press('Shift+Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'configurationNav');
  await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.id),'sidebarOpen');
  assert.equal(await page.locator('.app-bar').evaluate(el=>el.inert),false);
  await page.locator('#sidebarOpen').click();await page.locator('#premiumSetup').click();
  assert.equal(await page.locator('#premiumSetupDialog').evaluate(el=>el.open),true);
  assert.equal(await page.locator('#dashboardSidebar').getAttribute('aria-modal'),null);
  assert.equal(await page.evaluate(()=>document.activeElement.id),'premiumLicenceKey');
  await page.locator('#closePremiumSetup').click();
  assert.equal(await page.locator('#premiumLicenceKey').inputValue(),'');
  const bar=await page.locator('.app-bar').boundingBox(),refresh=await page.locator('#refresh').boundingBox();
  assert.ok(refresh.y>=bar.y&&refresh.y+refresh.height<=bar.y+bar.height,'Mobile header actions must stay inside the header, not overlap page content');
  await capture('mobile-configuration');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
  const preferencesUrl=new URL('/api/dashboard/preferences',started.url);
  const read=await(await fetch(preferencesUrl)).json();
  const foreign=await fetch(preferencesUrl,{method:'POST',headers:{'content-type':'application/json',origin:'https://outside.example'},body:JSON.stringify({confirmed:true,expectedDigest:read.digest,preferences:read.preferences})});assert.equal(foreign.status,403);
  const invalid=await fetch(preferencesUrl,{method:'POST',headers:{'content-type':'application/json',origin:started.url},body:JSON.stringify({confirmed:true,expectedDigest:read.digest,preferences:{optional_views:{portfolio:'true'}}})});assert.equal(invalid.status,400);
  const unknown=await fetch(preferencesUrl,{method:'POST',headers:{'content-type':'application/json',origin:started.url},body:JSON.stringify({confirmed:true,expectedDigest:read.digest,preferences:read.preferences,command:'do-not-run'})});assert.equal(unknown.status,400);
  const noOrigin=await fetch(preferencesUrl,{method:'POST',headers:{'content-type':'application/json'},body:'{}'});assert.equal(noOrigin.status,403);
  const wrongType=await fetch(preferencesUrl,{method:'POST',headers:{'content-type':'text/plain',origin:started.url},body:'{}'});assert.equal(wrongType.status,415);
  const malformed=await fetch(preferencesUrl,{method:'POST',headers:{'content-type':'application/json',origin:started.url},body:'{'});assert.equal(malformed.status,400);
  const wrongHost=await new Promise((resolveStatus,reject)=>{httpGet(preferencesUrl,{headers:{host:'outside.example'}},response=>{response.resume();resolveStatus(response.statusCode);}).on('error',reject);});assert.equal(wrongHost,403);
  const oversized=await fetch(preferencesUrl,{method:'POST',headers:{'content-type':'application/json',origin:started.url},body:' '.repeat(1024*1024+1)});assert.equal(oversized.status,413);
  assert.deepEqual(readDashboardPreferences(root).preferences,read.preferences);
});
