import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,rmSync,writeFileSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {execFileSync,spawn} from 'node:child_process';
import {once} from 'node:events';
import {buildOpenaiDecisionPayload,normaliseOpenaiDecisionResponse,openaiDecisionUsage} from '../src/openai-decisions.mjs';
import {readJevSettings,saveJevSettings,evaluateJev,readJevMeasurements,decisionCredentialIdentity,readDecisionCredentials} from '../src/jev.mjs';
import {initProject} from '../src/project.mjs';
import {createIntent} from '../src/intents.mjs';
import {prepareProjectContext} from '../src/runtime/context-assembly.mjs';
import {decideWithJev,recommendPersonasWithJev,prepareProjectContextWithJev,enrichImpactWithJev,readCompanionWithJev} from '../src/runtime/jev-operations.mjs';
const key=('sk-'+'synthetic-openai-fixture-not-a-real-key'),jevKey='apikey_synthetic-jev-fixture-not-a-real-key';
const questions={pick:{type:'choice',instructions:'Select relevant option',criteria:{yes:'Relevant',no:'Unrelated'}},score:{type:'score',instructions:'Relevance',criteria:['low','medium','high']},flag:{type:'noul',instructions:'Relevant?',criteria:{true:'Relevant',false:'Unrelated'}}};
const usage=()=>({input_tokens:100,input_tokens_details:{cached_tokens:0,cache_write_tokens:0},output_tokens:0,output_tokens_details:{reasoning_tokens:0},total_tokens:100});
function body(){return {model:'gpt-6-luna',answers:[{name:'pick',type:'choice',choice:'yes',confidence:0.9,probabilities:[{value:'yes',probability:0.9},{value:'no',probability:0.1}]},{name:'score',type:'score',score:1.9,confidence:0.9,probabilities:[{value:0,label:'low',probability:0},{value:1,label:'medium',probability:0.1},{value:2,label:'high',probability:0.9}]},{name:'flag',type:'predicate',probability:0.9}],usage:usage()};}
function fixture(t){const base=mkdtempSync(resolve(tmpdir(),'ewai-openai-decisions-')),root=resolve(base,'project'),home=resolve(base,'home');mkdirSync(root);mkdirSync(home,{mode:0o700});t.after(()=>rmSync(base,{recursive:true,force:true}));return {root,home,env:{OPENAI_API_KEY:key,TYPESAFE_API_KEY:jevKey}};}
function enable(f,patch={}){const before=readJevSettings(f.root);return saveJevSettings(f.root,{confirmed:true,expectedRevision:before.revision,policy:{...before.policy,mode:'shadow',provider:'auto',openaiConsent:true,cloudConsent:true,useCases:['claim','skill','personas'],...patch}});}
const input={useCase:'claim',source:'synthetic',state:{claim:'Synthetic bounded evidence'},questions};
test('optional off mode never resolves invalid credentials and a provider status failure stays isolated',async t=>{
 const f=fixture(t);enable(f,{mode:'off',provider:'openai'});const options={...f,env:{OPENAI_API_KEY:'invalid',TYPESAFE_API_KEY:jevKey},fetchImpl:()=>{throw Error('must not call');}};
 assert.equal(decisionCredentialIdentity(f.root,options),'local');assert.equal((await evaluateJev(f.root,input,options)).status,'disabled');
 const presence=readDecisionCredentials(f.root,options);assert.equal(presence.openaiCredentials.source,'unavailable');assert.equal(presence.openaiCredentials.configured,null);assert.equal(presence.credentials.configured,true);
 const p=await recommendPersonasWithJev(f.root,{focus:'Synthetic focus'},[{id:'fixture.persona',name:'Available reviewer',tier:'core'}],options);assert.equal(p.availableCount,1);assert.equal(p.consideredCount,0);assert.equal(p.recommendations.length,0);
});
test('primary-schema adapter preserves named choice, zero-based weighted score and predicate',()=>{
 const payload=buildOpenaiDecisionPayload(input.state,questions);assert.equal(payload.model,'gpt-6-luna');assert.equal(payload.input,JSON.stringify(input.state));assert.deepEqual(payload.questions[0].choices,[{value:'yes',description:'Relevant'},{value:'no',description:'Unrelated'}]);assert.deepEqual(payload.questions[1].levels,[{label:'low'},{label:'medium'},{label:'high'}]);assert.equal(payload.questions[2].type,'predicate');assert.match(payload.questions[2].instructions,/Relevant/);
 const result=normaliseOpenaiDecisionResponse(body(),questions);assert.equal(result.model,'jev-1.13.0');assert.equal(result.answers.pick.choice,'yes');assert.equal(result.answers.score.score,1.9);assert.deepEqual(result.answers.score.legend,{'0':'low','1':'medium','2':'high'});assert.equal(result.answers.flag.noul,0.9);
});
test('adapter rejects unknown, duplicated or incomplete answers and malformed typed distributions',()=>{
 for(const mutate of [v=>v.model='wrong',v=>v.answers.pop(),v=>v.answers[1].name='pick',v=>v.answers[0].choice=true,v=>v.answers[0].probabilities[0].probability=0.2,v=>v.answers[0].probabilities[1].value='yes',v=>v.answers[0].confidence=2,v=>v.answers[1].probabilities[2].label='invented',v=>v.answers[1].probabilities[2].value='2',v=>v.answers[1].score=1,v=>v.answers[2].probability=-1]){const b=body();mutate(b);assert.throws(()=>normaliseOpenaiDecisionResponse(b,questions));}
 const b=body();b.answers[0]={name:'pick',type:'refusal'};assert.throws(()=>normaliseOpenaiDecisionResponse(b,questions),/refusal/);
});
test('rubric scores outside either endpoint are rejected even within rounding tolerance',()=>{
 for(const [score,probabilities]of [[-0.009,[1,0,0]],[2.009,[0,0,1]]]){const b=body();b.answers[1].score=score;b.answers[1].probabilities.forEach((p,i)=>p.probability=probabilities[i]);assert.throws(()=>normaliseOpenaiDecisionResponse(b,questions));}
});
test('refused and malformed advice preserve all known cache and reasoning usage details',async t=>{
 for(const refusal of [true,false]){const f=fixture(t);enable(f);const b=body();b.usage={input_tokens:100,input_tokens_details:{cached_tokens:30,cache_write_tokens:10},output_tokens:10,output_tokens_details:{reasoning_tokens:5},total_tokens:110};if(refusal)b.answers[0]={name:'pick',type:'refusal'};else b.answers[1].score=99;const r=await evaluateJev(f.root,input,{...f,fetchImpl:async()=>new Response(JSON.stringify(b))});assert.equal(r.status,'fallback');assert.equal(r.measurement.cachedTokens,30);assert.equal(r.measurement.cacheWriteTokens,10);assert.equal(r.measurement.reasoningTokens,5);assert.equal(r.measurement.inputTokens,100);assert.equal(r.measurement.estimatedUSD,0.00001);}
});
test('CLI can revoke each vendor separately without silently removing the other consent',t=>{
 const f=fixture(t);initProject(f.root,{name:'Synthetic CLI consent parity'});enable(f);const cli=resolve(import.meta.dirname,'../bin/ewai'),env={...process.env,HOME:f.home,TYPESAFE_API_KEY:'',OPENAI_API_KEY:''};const run=args=>JSON.parse(execFileSync(process.execPath,[cli,'decisions','configure',...args,'--yes','--project',f.root,'--json'],{env,encoding:'utf8'}));
 let r=run(['--revoke-openai-processing']);assert.equal(r.policy.openaiConsent,false);assert.equal(r.policy.cloudConsent,true);assert.equal(r.policy.mode,'shadow');r=run(['--acknowledge-openai-processing','--revoke-cloud-processing']);assert.equal(r.policy.openaiConsent,true);assert.equal(r.policy.cloudConsent,false);r=run(['--mode','off','--revoke-openai-processing']);assert.equal(r.policy.openaiConsent,false);assert.equal(r.policy.cloudConsent,false);assert.equal(r.policy.mode,'off');
 const before=readJevSettings(f.root);assert.throws(()=>run(['--acknowledge-openai-processing','--revoke-openai-processing']));assert.deepEqual(readJevSettings(f.root),before);
});
test('usage validates documented totals and details independently of refused answers',()=>{
 assert.deepEqual(openaiDecisionUsage(body()),{inputTokens:100,outputTokens:0,cachedTokens:0,cacheWriteTokens:0,reasoningTokens:0});
 for(const mutate of [v=>v.usage.input_tokens=-1,v=>v.usage.total_tokens=99,v=>v.usage.input_tokens_details.cached_tokens=101,v=>v.usage.output_tokens_details.reasoning_tokens=1,v=>delete v.usage.total_tokens,v=>v.usage.input_tokens_details.cached_tokens=NaN]){const b=body();mutate(b);assert.equal(openaiDecisionUsage(b),null);}
});
test('new settings start off and Automatic; legacy settings preserve Jev consent and unknown fields fail closed',t=>{
 const f=fixture(t),fresh=readJevSettings(f.root);assert.equal(fresh.policy.mode,'off');assert.equal(fresh.policy.provider,'auto');assert.equal(fresh.policy.openaiConsent,false);
 const legacy={...fresh.policy,mode:'shadow',cloudConsent:true};delete legacy.provider;delete legacy.openaiConsent;mkdirSync(resolve(f.root,'.ewai-pipeline'));writeFileSync(resolve(f.root,'.ewai-pipeline/jev.json'),JSON.stringify({schema:'ewai.jev-settings/v1',revision:'missing',policy:legacy}),{mode:0o600});
 const migrated=readJevSettings(f.root);assert.equal(migrated.policy.provider,'jev');assert.equal(migrated.policy.openaiConsent,false);assert.equal(migrated.policy.mode,'shadow');
 for(const patch of [{provider:'unknown'},{openaiConsent:'yes'},{provider:'openai',openaiConsent:false},{endpoint:'https://outside.invalid'}])assert.throws(()=>enable(f,patch));
});
test('Automatic selects authorised OpenAI and returns normalised advice with exact provider cache',async t=>{
 const f=fixture(t);enable(f);let calls=0;const fetchImpl=async(url,init)=>{calls++;assert.equal(url,'https://api.openai.com/v1/decisions');assert.equal(init.redirect,'manual');assert.equal(init.headers.authorization,'Bearer '+key);assert.equal(JSON.parse(init.body).questions.length,3);return new Response(JSON.stringify(body()));};
 const first=await evaluateJev(f.root,input,{...f,fetchImpl});assert.equal(first.status,'suggested');assert.equal(first.measurement.provider,'openai');assert.equal(first.measurement.model,'gpt-6-luna');assert.equal(first.measurement.estimatedUSD,0.00001);assert.equal(first.answers.flag.noul,0.9);
 assert.equal((await evaluateJev(f.root,input,{...f,fetchImpl})).cacheHit,true);assert.equal(calls,1);assert.equal(readJevMeasurements(f.root).summary.estimatedUSD,0.00001);
 const stored=readFileSync(resolve(f.root,'.ewai-pipeline/runtime/jev/state.json'),'utf8');assert.ok(!stored.includes(key));assert.ok(!stored.includes('Synthetic bounded evidence'));assert.ok(!stored.includes('Select relevant option'));
});
test('Automatic falls back to Jev only before dispatch when OpenAI key or separate consent is absent',async t=>{
 for(const env of [{TYPESAFE_API_KEY:jevKey},{OPENAI_API_KEY:key,TYPESAFE_API_KEY:jevKey}]){const f=fixture(t);enable(f,{openaiConsent:false});let calls=0;const result=await evaluateJev(f.root,{...input,questions:{pick:questions.pick}},{...f,env,fetchImpl:async url=>{calls++;assert.equal(url,'https://api.typesafe.ai/v1/systemone');return new Response(JSON.stringify({model:'jev-1.13.0',answers:{pick:{type:'choice',choice:'yes',confidence:1,probabilities:{yes:1,no:0}}},usage:{input_tokens:100,output_tokens:0}}));}});assert.equal(result.status,'suggested');assert.equal(result.measurement.provider,'jev');assert.equal(calls,1);}
 const f=fixture(t);enable(f,{provider:'openai'});assert.equal((await evaluateJev(f.root,input,{...f,env:{TYPESAFE_API_KEY:jevKey},fetchImpl:()=>{throw Error('must not dispatch');}})).reason,'missing-key');
});
test('refusal and invalid answers keep known costs; network failure never sends a second paid request',async t=>{
 for(const outcome of ['refusal','wrong-model','timeout','http']){const f=fixture(t);enable(f,{timeoutMs:100});let calls=0;const fetchImpl=async()=>{calls++;if(outcome==='timeout')return new Promise(()=>{});if(outcome==='http')return new Response(key,{status:403});const b=body();if(outcome==='refusal')b.answers[0]={name:'pick',type:'refusal'};else b.model='wrong';return new Response(JSON.stringify(b));};const result=await evaluateJev(f.root,input,{...f,fetchImpl});assert.equal(result.status,'fallback');assert.equal(result.answers,undefined);assert.equal(calls,1);assert.ok(!JSON.stringify(result).includes(key));assert.equal(result.measurement.inputTokens,['refusal','wrong-model'].includes(outcome)?100:null);if(outcome==='refusal')assert.equal(result.reason,'refusal');if(outcome==='timeout'){assert.equal((await evaluateJev(f.root,input,{...f,fetchImpl})).reason,'budget-exhausted');assert.equal(calls,1);}}
});
test('credential priority changes invalidate in-flight Jev results and OpenAI cached identity',async t=>{
 const f=fixture(t);enable(f);const env={TYPESAFE_API_KEY:jevKey};let release;const pending=evaluateJev(f.root,{...input,questions:{pick:questions.pick}},{...f,env,fetchImpl:()=>new Promise(r=>{release=()=>r(new Response(JSON.stringify({model:'jev-1.13.0',answers:{pick:{type:'choice',choice:'yes',confidence:1,probabilities:{yes:1,no:0}}},usage:{input_tokens:100,output_tokens:0}})));})});const old=decisionCredentialIdentity(f.root,{...f,env});env.OPENAI_API_KEY=key;assert.notEqual(decisionCredentialIdentity(f.root,{...f,env}),old);release();assert.equal((await pending).reason,'policy-changed');
 let calls=0;const fetchImpl=async()=>{calls++;return new Response(JSON.stringify(body()));};await evaluateJev(f.root,input,{...f,fetchImpl});f.env.OPENAI_API_KEY=('sk-'+'synthetic-other-openai-fixture-key');await evaluateJev(f.root,input,{...f,fetchImpl});assert.equal(calls,2);
});
test('the shared budget and per-provider costs survive a policy change without repricing previous Jev tokens',async t=>{
 const f=fixture(t);enable(f,{provider:'jev'});const jev={model:'jev-1.13.0',answers:{pick:{type:'choice',choice:'yes',confidence:1,probabilities:{yes:1,no:0}}},usage:{input_tokens:100,output_tokens:0}};await evaluateJev(f.root,{...input,questions:{pick:questions.pick}},{...f,fetchImpl:async()=>new Response(JSON.stringify(jev))});enable(f,{maxCalls:1});assert.equal((await evaluateJev(f.root,input,{...f,fetchImpl:async()=>new Response(JSON.stringify(body()))})).status,'suggested');assert.equal((await evaluateJev(f.root,{...input,state:'new'},{...f,fetchImpl:()=>{throw Error('no more calls');}})).reason,'budget-exhausted');const s=readJevMeasurements(f.root).summary;assert.equal(s.inputTokens,200);assert.ok(Math.abs(s.estimatedUSD-0.0000142)<1e-12);assert.equal(s.downstreamSavings,null);
});
test('a credential change between key resolution and identity capture cannot dispatch the predecessor key',async t=>{
 const f=fixture(t);enable(f);let reads=0,calls=0;const env={TYPESAFE_API_KEY:jevKey};
 Object.defineProperty(env,'OPENAI_API_KEY',{get(){reads++;return reads<=2?key:('sk-'+'synthetic-replacement-fixture-key');}});
 const result=await evaluateJev(f.root,input,{...f,env,fetchImpl:async()=>{calls++;return new Response(JSON.stringify(body()));}});
 assert.equal(result.reason,'policy-changed');assert.equal(calls,0);assert.equal(result.answers,undefined);
});
test('OpenAI whole-body deadline, unknown source and secret filters retain zero or one paid-call boundaries',async t=>{
 const f=fixture(t);enable(f,{timeoutMs:100});let calls=0;const fetchImpl=async()=>{calls++;return new Response(new ReadableStream({start(){}}));};for(const patch of [{source:'imported'},{state:{api_key:key}},{state:JSON.stringify({password:'private-value'})}])assert.equal((await evaluateJev(f.root,{...input,...patch},{...f,fetchImpl})).status,'fallback');assert.equal(calls,0);assert.equal((await evaluateJev(f.root,input,{...f,fetchImpl})).reason,'timeout');assert.equal(calls,1);assert.equal(readJevMeasurements(f.root).summary.estimatedUSD,null);
});
test('OpenAI recommendations compare an LLM option and recommend only available persona metadata',async t=>{
 const f=fixture(t);enable(f);const fetchImpl=async(_url,init)=>{const payload=JSON.parse(init.body);return new Response(JSON.stringify({model:'gpt-6-luna',answers:payload.questions.map(q=>q.type==='score'?{name:q.name,type:'score',score:q.levels.length-1,confidence:1,probabilities:q.levels.map((l,i)=>({value:i,label:l.label,probability:i===q.levels.length-1?1:0}))}:{name:q.name,type:'choice',choice:q.choices[0].value,confidence:1,probabilities:q.choices.map((c,i)=>({value:c.value,probability:i===0?1:0}))}),usage:usage()}));};
 const advice=await decideWithJev(f.root,{useCase:'skill',source:'synthetic',origin:'llm',recommendedId:'a',task:'Synthetic option',candidates:[{id:'a',label:'Relevant'},{id:'b',label:'Other'}]},{...f,fetchImpl});assert.equal(advice.status,'suggested');assert.equal(advice.validation.status,'agrees');
 const personas=await recommendPersonasWithJev(f.root,{focus:'Synthetic security review',limit:1},[{id:'persona.fixture',name:'Security reviewer',tier:'premium',source:'premium',path:'/fixture/persona.md',body:'PRIVATE PERSONA BODY'}],{...f,fetchImpl});assert.equal(personas.status,'suggested');assert.ok(personas.recommendations.length<=1);
});

function openaiTransport(_url,init){const request=JSON.parse(init.body);assert.equal(request.model,'gpt-6-luna');return Promise.resolve(new Response(JSON.stringify({model:'gpt-6-luna',answers:request.questions.map(q=>{if(q.type==='score'){const last=q.levels.length-1;return {name:q.name,type:'score',score:last,confidence:1,probabilities:q.levels.map((l,i)=>({value:i,label:l.label,probability:i===last?1:0}))};}if(q.type==='predicate')return {name:q.name,type:'predicate',probability:1};const choice=q.choices.find(c=>['security','insufficient'].includes(c.value))?.value??q.choices[0].value;return {name:q.name,type:'choice',choice,confidence:1,probabilities:q.choices.map(c=>({value:c.value,probability:c.value===choice?1:0}))};}),usage:usage()})));}
function workFixture(t,mode){const f=fixture(t);initProject(f.root,{name:'Synthetic OpenAI operation parity'});createIntent(f.root,{slug:'synthetic',domain:'platform',title:'Synthetic optional assistance',details:{problem:'Keep optional advice bounded',outcomes:'PRIVATE MANDATORY EVIDENCE'}});enable(f,{mode,useCases:['context','personas','skill','claim','failure','impact','tests']});return f;}
test('OpenAI shadow and active cover all seven rubrics and protect mandatory tests and local quotes',async t=>{
 for(const mode of ['shadow','active']){const f=workFixture(t,mode);for(const useCase of ['context','personas','skill','claim','failure','impact','tests']){const r=await decideWithJev(f.root,{useCase,source:'synthetic',task:'Synthetic decision',candidates:[{id:'optional',label:'Optional'},{id:'required',label:'Mandatory',mandatory:true}],claim:'Synthetic claim',evidence:'Synthetic evidence',diagnostic:{code:'HTTP-401',message:'Request rejected'},summary:'Synthetic impact'},{...f,fetchImpl:openaiTransport});assert.equal(r.status,'suggested');assert.equal(r.mode,mode);assert.equal(r.authority,'advisory');assert.equal(r.measurement.provider,'openai');if(useCase==='tests')assert.deepEqual(r.requiredIds,['required']);}
  const quote=await decideWithJev(f.root,{useCase:'claim',source:'synthetic',claim:'A',evidence:'B',quote:'Absent'},{...f,fetchImpl:()=>{throw Error('must not call');}});assert.equal(quote.reason,'quote-absent');
 }
});
test('OpenAI context keeps the shadow baseline, exact active personas, protected routes and fresh overflow',async t=>{
 const f=workFixture(t,'shadow'),catalogue=[{id:'same',name:'Core definition',tier:'core',tags:[]},{id:'same',name:'Project definition',tier:'project',tags:['unmatched-specialism']},{id:'premium.fixture',name:'Installed premium reviewer',tier:'premium',tags:[],body:'PRIVATE PREMIUM BODY'}],ctx={profile:'intent',slug:'synthetic',focus:'security',personaCatalogue:catalogue};prepareProjectContext(f.root,ctx);const baseline=prepareProjectContext(f.root,ctx),fetchImpl=async(url,init)=>{assert.ok(!init.body.includes('PRIVATE'));return openaiTransport(url,init);};assert.deepEqual(await prepareProjectContextWithJev(f.root,ctx,{...f,fetchImpl}),baseline);
 enable(f,{mode:'active',useCases:['context','personas','skill','claim','failure','impact','tests']});const active=await prepareProjectContextWithJev(f.root,ctx,{...f,fetchImpl});assert.equal(active.fidelity.mandatoryRecall,1);for(const p of baseline.activePersonas)assert.deepEqual(active.activePersonas.find(a=>a.id===p.id),p);assert.equal(active.activePersonas.find(a=>a.id==='same').name,'Project definition');assert.equal(active.activePersonas.find(a=>a.id==='same').tier,'project');
 const impact={summary:'Synthetic privacy impact',activePersonas:baseline.activePersonas,reviewRoutes:[{id:'maintainer',recommendation:'required'}]},enriched=await enrichImpactWithJev(f.root,impact,{...f,fetchImpl});assert.deepEqual(enriched.reviewRoutes,impact.reviewRoutes);assert.deepEqual(enriched.activePersonas,impact.activePersonas);assert.ok(enriched.impactAreas.some(a=>a.label.includes('OpenAI Decisions suggests')));
 const overflow=await prepareProjectContextWithJev(f.root,{...ctx,budgetTokens:1},{...f,fetchImpl:()=>{throw Error('must not call');}});assert.equal(overflow.status,'non-ready');assert.equal(overflow.modelContext,null);
 const changed=await prepareProjectContextWithJev(f.root,{...ctx,focus:'uncached source-change focus'},{...f,fetchImpl:async(url,init)=>{writeFileSync(resolve(f.root,'SPECS/2.Purpose/intents/platform/synthetic.md'),'Changed mandatory evidence. '.repeat(30000));return openaiTransport(url,init);}});assert.equal(changed.status,'non-ready');assert.equal(changed.modelContext,null);assert.equal(changed.reason,'mandatory-overflow');
});
test('OpenAI companion ranking preserves human and blocked slots with original focus and governed handoffs',async t=>{
 const f=workFixture(t,'active'),items=[{id:'human',slug:'human',title:'Approval',lane:'qa'},{id:'one',slug:'one',title:'Alpha',execution:{actions:{beginHarness:{permitted:true}}}},{id:'two',slug:'two',title:'Beta',execution:{actions:{beginHarness:{permitted:true}}}},{id:'blocked',slug:'blocked',title:'Blocked',lane:'blocked'}];const r=await readCompanionWithJev(f.root,{...f,items,personas:[],focus:'security',fetchImpl:async(_url,init)=>{const request=JSON.parse(init.body),q=request.questions[0],choice=q.choices.find(c=>c.description.includes('Beta')).value;return new Response(JSON.stringify({model:'gpt-6-luna',answers:[{name:q.name,type:'choice',choice,confidence:1,probabilities:q.choices.map(c=>({value:c.value,probability:c.value===choice?1:0}))}],usage:usage()}));}});assert.equal(r.recommendations[0].id,'human');assert.equal(r.recommendations.at(-1).id,'blocked');assert.equal(r.recommendations[1].id,'two');assert.equal(r.recommendations[1].handoff.kind,'begin');assert.equal(r.focus,'security');assert.equal(r.spotlight.id,'human');
});
test('killed OpenAI dispatch leaves unresolved cost and blocks Jev in the same shared budget', {timeout:10000},async t=>{
 const f=fixture(t);enable(f);const path=resolve(f.root,'worker.mjs');writeFileSync(path,`import {evaluateJev} from ${JSON.stringify(new URL('../src/jev.mjs',import.meta.url).href)};await evaluateJev(process.env.OPENAI_TEST_PROJECT,${JSON.stringify(input)},{home:process.env.OPENAI_TEST_HOME,env:{OPENAI_API_KEY:['sk','synthetic-crash-fixture-key'].join('-')},fetchImpl:()=>{process.send('dispatched');return new Promise(()=>{});}});`);
 const child=spawn(process.execPath,[path],{env:{...process.env,OPENAI_TEST_PROJECT:f.root,OPENAI_TEST_HOME:f.home},stdio:['ignore','ignore','ignore','ipc']});t.after(()=>child.kill('SIGKILL'));await once(child,'message');const exited=once(child,'exit');child.kill('SIGKILL');await exited;const before=readJevMeasurements(f.root);assert.equal(before.summary.unresolvedCalls,1);assert.equal(before.summary.estimatedUSD,null);assert.equal((await evaluateJev(f.root,input,{...f,env:{TYPESAFE_API_KEY:jevKey},fetchImpl:()=>{throw Error('must not dispatch');}})).reason,'budget-exhausted');enable(f,{mode:'off'});assert.equal(readJevMeasurements(f.root).summary.estimatedUSD,null);
});
test('explicit unavailable vendors remain optional for personas and fresh context, including mid-flight source overflow',async t=>{
 for(const provider of ['openai','jev']){
  const f=workFixture(t,'active');enable(f,{mode:'active',provider,useCases:['context','personas']});const variable=provider==='openai'?'OPENAI_API_KEY':'TYPESAFE_API_KEY',valid=f.env[variable],catalogue=[{id:'fixture.persona',name:'Available security reviewer',tier:'core',tags:['security']}],ctx={profile:'intent',slug:'synthetic',focus:'security',personaCatalogue:catalogue};prepareProjectContext(f.root,ctx);const baseline=prepareProjectContext(f.root,ctx);f.env[variable]='invalid';
  const unavailable=await recommendPersonasWithJev(f.root,{focus:'security'},catalogue,{...f,fetchImpl:()=>{throw Error('must not call');}});assert.equal(unavailable.status,'fallback');assert.equal(unavailable.availableCount,1);assert.equal(unavailable.consideredCount,0);assert.deepEqual(unavailable.recommendations,[]);assert.deepEqual(await prepareProjectContextWithJev(f.root,ctx,{...f,fetchImpl:()=>{throw Error('must not call');}}),baseline);
  f.env[variable]=valid;let calls=0;const result=await prepareProjectContextWithJev(f.root,{...ctx,focus:'uncached mutation focus'},{...f,fetchImpl:async(url,init)=>{calls++;f.env[variable]='invalid';writeFileSync(resolve(f.root,'SPECS/2.Purpose/intents/platform/synthetic.md'),'Changed mandatory source. '.repeat(30000));if(provider==='openai')return openaiTransport(url,init);const request=JSON.parse(init.body);return new Response(JSON.stringify({model:'jev-1.13.0',answers:Object.fromEntries(Object.entries(request.questions).map(([id,q])=>[id,{type:'score',score:1,confidence:1,legend:{'0':q.criteria[0],'1':q.criteria[1]},probabilities:{'0':0,'1':1}}])),usage:{input_tokens:100,output_tokens:0}}));}});
  assert.equal(calls,1);assert.equal(result.status,'non-ready');assert.equal(result.modelContext,null);assert.equal(result.reason,'mandatory-overflow');
 }
});
