import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,rmSync,readFileSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
import {initProject} from '../src/project.mjs';
import {ensureDashboard,stopDashboard} from '../src/runtime/dashboard.mjs';
import {readJevSettings} from '../src/jev.mjs';
import {chromium} from 'playwright';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
async function fixture(t,mockAuth=false){const base=mkdtempSync(resolve(tmpdir(),'ewai-openai-ui-')),home=resolve(base,'home'),project=resolve(base,'project');mkdirSync(home,{mode:0o700});mkdirSync(project);initProject(project,{name:'Synthetic OpenAI UI'});t.after(async()=>{await stopDashboard(project);rmSync(base,{recursive:true,force:true,maxRetries:5,retryDelay:200});});const previous=process.env.NODE_OPTIONS,preload=resolve(base,'preload.mjs');let url;try{if(mockAuth){writeFileSync(preload,`import {appendFileSync} from 'node:fs';const original=globalThis.fetch;globalThis.fetch=async(url,init)=>{if(String(url)==='https://api.openai.com/v1/models'){appendFileSync(${JSON.stringify(resolve(base,'calls.txt'))},'authentication\\n');return new Response('{\"data\":[]}');}if(/^https:/.test(String(url)))throw Error('External fixture transport blocked');return original(url,init);};`);process.env.NODE_OPTIONS=(previous??'')+' --import='+preload;}({url}=await ensureDashboard(project,{home,premiumCheck:Promise.resolve({access:'unavailable',installed:false,verified:false,accessReason:'licence-not-configured'})}));}finally{if(previous===undefined)delete process.env.NODE_OPTIONS;else process.env.NODE_OPTIONS=previous;}return {home,project,url,base};}
test('private OpenAI HTTP route guards origin, method, queries, media type, size and primitive roots',{timeout:60000},async t=>{
 const f=await fixture(t),endpoint=f.url+'/api/openai/credentials',status=await fetch(endpoint);assert.equal(status.status,200);const s=await status.json();assert.equal(s.configured,false);
 const input={confirmed:true,expectedRevision:s.revision,apiKey:'invalid'},headers={origin:f.url,'content-type':'application/json'};
 assert.equal((await fetch(endpoint+'/configure',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)})).status,403);
 assert.equal((await fetch(endpoint+'/configure',{method:'POST',headers:{origin:'https://outside.invalid','content-type':'application/json'},body:JSON.stringify(input)})).status,403);
 assert.equal((await fetch(endpoint+'?apiKey=forbidden')).status,400);assert.equal((await fetch(endpoint,{method:'PUT'})).status,405);
 assert.equal((await fetch(endpoint+'/configure',{method:'POST',headers:{origin:f.url,'content-type':'text/plain'},body:'{}'})).status,415);
 for(const body of ['null','[]','true','1','"text"',JSON.stringify({...input,projectRoot:'/outside'}),JSON.stringify({...input,confirmed:false}),JSON.stringify(input)]){const r=await fetch(endpoint+'/configure',{method:'POST',headers,body});assert.equal(r.status,400);assert.ok(!(await r.text()).includes('/outside'));assert.equal((await fetch(f.url+'/api/health')).status,200);}
 assert.equal((await fetch(endpoint+'/configure',{method:'POST',headers,body:JSON.stringify({...input,apiKey:'x'.repeat(3000)})})).status,413);
 assert.equal(readJevSettings(f.project).policy.mode,'off');
});
test('Automatic preference, independent vendor consents and password clearing work in the selected mobile UI',{timeout:60000},async t=>{
 const f=await fixture(t),browser=await chromium.launch({headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:390,height:844}}),key=('sk-'+'synthetic-dashboard-fixture-key');
 await page.route('**/api/openai/credentials/configure',route=>route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({code:'openai-key-rejected',error:'The key was not accepted.'})}));
 await page.goto(f.url);await page.locator('#sidebarOpen').click();await page.locator('#configurationNav:enabled').click();assert.equal(await page.locator('#jevProvider').inputValue(),'auto');await page.locator('#openaiCredentialKey:enabled').fill(key);await page.locator('#openaiCredentialCancel').click();assert.equal(await page.locator('#openaiCredentialKey').inputValue(),'');await page.locator('#openaiCredentialKey').fill(key);await page.locator('#openaiCredentialSave').click();await page.locator('#openaiCredentialNotice').getByText(/not accepted/).waitFor();assert.equal(await page.locator('#openaiCredentialKey').inputValue(),'');assert.equal(readJevSettings(f.project).policy.mode,'off');
 await page.locator('#jevProvider').selectOption('openai');await page.locator('input[name=jevMode][value=shadow]').check();await page.locator('#jevCloudConsent').check();await page.locator('#jevSettingsSave').click();await page.locator('#jevNotice').getByText(/consent|disclosure/i).waitFor();assert.equal(readJevSettings(f.project).policy.mode,'off');
 await page.locator('#openaiCloudConsent').check();await page.locator('#jevSettingsSave').click();await page.locator('#jevNotice').getByText(/settings saved.*shadow/i).waitFor();assert.equal(readJevSettings(f.project).policy.provider,'openai');assert.equal(readJevSettings(f.project).policy.openaiConsent,true);
 const current=await(await fetch(f.url+'/api/decisions/settings')).json();await fetch(f.url+'/api/decisions/settings',{method:'POST',headers:{origin:f.url,'content-type':'application/json'},body:JSON.stringify({confirmed:true,expectedRevision:current.revision,policy:{...current.policy,mode:'off'}})});await page.locator('#jevSettingsSave').click();await page.locator('#jevNotice').getByText(/changed.*refresh/i).waitFor();assert.equal(readJevSettings(f.project).policy.mode,'off');
 await page.locator('#openaiCredentialKey').fill(key);await page.locator('#openaiCredentialRefresh').click();assert.equal(await page.locator('#openaiCredentialKey').inputValue(),'');assert.equal(await page.evaluate(k=>JSON.stringify(localStorage).includes(k)||JSON.stringify(sessionStorage).includes(k),key),false);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
});
test('CLI and MCP provider-neutral aliases preserve closed input and off behaviour',{timeout:60000},async t=>{
 const f=await fixture(t),cli=resolve(import.meta.dirname,'../bin/ewai'),env={...process.env,HOME:f.home,OPENAI_API_KEY:'',TYPESAFE_API_KEY:''};const status=JSON.parse(execFileSync(process.execPath,[cli,'decisions','status','--project',f.project,'--json'],{env,encoding:'utf8'}));assert.equal(status.settings.policy.provider,'auto');assert.equal(status.openaiCredentials.configured,false);
 const client=new Client({name:'decisions-fixture',version:'1'});t.after(()=>client.close());await client.connect(new StdioClientTransport({command:process.execPath,args:[cli,'mcp','--project',f.project],env,stderr:'ignore'}));const tools=(await client.listTools()).tools;for(const action of ['status','configure','measurements','decide','personas'])assert.ok(tools.some(t=>t.name==='ewai_decisions_'+action));const result=JSON.parse((await client.callTool({name:'ewai_decisions_status',arguments:{}})).content[0].text);assert.equal(result.openaiCredentials.configured,false);assert.equal((await client.callTool({name:'ewai_decisions_status',arguments:{apiKey:'forbidden'}})).isError,true);assert.ok(!tools.some(t=>/^ewai.*openai.*configure/.test(t.name)));
 const input={useCase:'skill',source:'synthetic',task:'Synthetic option',candidates:[{id:'one',label:'Only option'}]};assert.equal(JSON.parse((await client.callTool({name:'ewai_decisions_decide',arguments:input})).content[0].text).status,'disabled');
});

test('successful private dashboard capture checks only metadata, keeps decisions off and supports stale-safe removal',{timeout:60000},async t=>{
 const f=await fixture(t,true),browser=await chromium.launch({headless:true});t.after(()=>browser.close());const page=await browser.newPage(),key=['sk','synthetic-successful-ui-fixture-key'].join('-');await page.goto(f.url);await page.locator('#configurationNav:enabled').click();await page.locator('#openaiCredentialKey:enabled').fill(key);await page.locator('#openaiCredentialSave').click();await page.locator('#openaiCredentialNotice').getByText(/checked and saved/).waitFor();assert.equal(await page.locator('#openaiCredentialKey').inputValue(),'');assert.equal(readJevSettings(f.project).policy.mode,'off');const endpoint=f.url+'/api/openai/credentials',status=await(await fetch(endpoint)).json();assert.equal(status.source,'saved');assert.ok(!JSON.stringify(status).includes(key));assert.equal(readFileSync(resolve(f.base,'calls.txt'),'utf8').trim(),'authentication');const headers={origin:f.url,'content-type':'application/json'};
 const stale=await fetch(endpoint+'/configure',{method:'POST',headers,body:JSON.stringify({confirmed:true,expectedRevision:'missing',apiKey:key})});assert.equal(stale.status,409);assert.equal((await(await fetch(endpoint)).json()).revision,status.revision);assert.equal(readFileSync(resolve(f.base,'calls.txt'),'utf8').trim(),'authentication');await page.locator('#openaiCredentialRemove').click();await page.locator('#openaiCredentialNotice').getByText(/Saved OpenAI key removed/).waitFor();assert.equal((await(await fetch(endpoint)).json()).configured,false);assert.equal(readJevSettings(f.project).policy.mode,'off');
});

test('MCP and dashboard can revoke one consent while retaining the other and then return to off',{timeout:60000},async t=>{
 const f=await fixture(t),client=new Client({name:'consent-parity',version:'1'}),cli=resolve(import.meta.dirname,'../bin/ewai');t.after(()=>client.close());await client.connect(new StdioClientTransport({command:process.execPath,args:[cli,'mcp','--project',f.project],env:{...process.env,HOME:f.home,OPENAI_API_KEY:'',TYPESAFE_API_KEY:''},stderr:'ignore'}));let settings=readJevSettings(f.project);const mcpSave=async policy=>{const r=await client.callTool({name:'ewai_decisions_configure',arguments:{confirmed:true,expectedRevision:settings.revision,policy}});assert.ok(!r.isError);settings=JSON.parse(r.content[0].text);};
 await mcpSave({...settings.policy,mode:'shadow',provider:'auto',openaiConsent:true,cloudConsent:true});await mcpSave({...settings.policy,openaiConsent:false});assert.equal(settings.policy.openaiConsent,false);assert.equal(settings.policy.cloudConsent,true);
 const browser=await chromium.launch({headless:true});t.after(()=>browser.close());const page=await browser.newPage();await page.goto(f.url);await page.locator('#configurationNav:enabled').click();await page.locator('#jevSettingsSave:enabled').waitFor();await page.locator('#openaiCloudConsent').check();await page.locator('#jevCloudConsent').uncheck();await page.locator('#jevSettingsSave').click();await page.locator('#jevNotice').getByText('Decision settings saved. Mode: shadow.',{exact:true}).waitFor();settings=readJevSettings(f.project);assert.equal(settings.policy.openaiConsent,true);assert.equal(settings.policy.cloudConsent,false);await page.locator('input[name=jevMode][value=off]').check();await page.locator('#openaiCloudConsent').uncheck();await page.locator('#jevSettingsSave').click();await page.locator('#jevNotice').getByText('Decision settings saved. Mode: off.',{exact:true}).waitFor();settings=readJevSettings(f.project);assert.equal(settings.policy.openaiConsent,false);assert.equal(settings.policy.cloudConsent,false);assert.equal(settings.policy.mode,'off');
});
